src/Entity/Clientes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClientesRepository")
 */
class Clientes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nit;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="clientes")
     */
    private $IdUsuario;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contactoPrincipal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $correo;

    /**
     * @ORM\Column(type="date")
     */
    private $fechaNacimiento;

    

    /**
     * @ORM\Column(type="text")
     */
    private $comentarios;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zona;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $dpto;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $municipio;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telefonoMovil;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telefonoLocal;

    /**
     * @ORM\Column(type="text")
     */
    private $direccion;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Facturas", mappedBy="idcliente", cascade={"persist", "remove"})
     */
    private $facturas;

    /**
     * @ORM\Column(type="date")
     */
    private $ingreso;

    public function __construct()
    {
        $this->facturas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getNit(): ?string
    {
        return $this->nit;
    }

    public function setNit(string $nit): self
    {
        $this->nit = $nit;

        return $this;
    }

    public function getIdUsuario(): ?User
    {
        return $this->IdUsuario;
    }

    public function setIdUsuario(?User $IdUsuario): self
    {
        $this->IdUsuario = $IdUsuario;

        return $this;
    }

    public function getContactoPrincipal(): ?string
    {
        return $this->contactoPrincipal;
    }

    public function setContactoPrincipal(string $contactoPrincipal): self
    {
        $this->contactoPrincipal = $contactoPrincipal;

        return $this;
    }

    public function getCorreo(): ?string
    {
        return $this->correo;
    }

    public function setCorreo(string $correo): self
    {
        $this->correo = $correo;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fechaNacimiento;
    }

    public function setFechaNacimiento(\DateTimeInterface $fechaNacimiento): self
    {
        $this->fechaNacimiento = $fechaNacimiento;

        return $this;
    }

    public function getComentarios(): ?string
    {
        return $this->comentarios;
    }

    public function setComentarios(string $comentarios): self
    {
        $this->comentarios = $comentarios;

        return $this;
    }

    public function getZona(): ?string
    {
        return $this->zona;
    }

    public function setZona(string $zona): self
    {
        $this->zona = $zona;

        return $this;
    }

    public function getDpto(): ?string
    {
        return $this->dpto;
    }

    public function setDpto(string $dpto): self
    {
        $this->dpto = $dpto;

        return $this;
    }

    public function getMunicipio(): ?string
    {
        return $this->municipio;
    }

    public function setMunicipio(string $municipio): self
    {
        $this->municipio = $municipio;

        return $this;
    }

    public function getTelefonoMovil(): ?string
    {
        return $this->telefonoMovil;
    }

    public function setTelefonoMovil(string $telefonoMovil): self
    {
        $this->telefonoMovil = $telefonoMovil;

        return $this;
    }

    public function getTelefonoLocal(): ?string
    {
        return $this->telefonoLocal;
    }

    public function setTelefonoLocal(string $telefonoLocal): self
    {
        $this->telefonoLocal = $telefonoLocal;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    /**
     * @return Collection|Facturas[]
     */
    public function getFacturas(): Collection
    {
        return $this->facturas;
    }

    public function addFactura(Facturas $factura): self
    {
        if (!$this->facturas->contains($factura)) {
            $this->facturas[] = $factura;
            $factura->setIdcliente($this);
        }

        return $this;
    }

    public function removeFactura(Facturas $factura): self
    {
        if ($this->facturas->contains($factura)) {
            $this->facturas->removeElement($factura);
            // set the owning side to null (unless already changed)
            if ($factura->getIdcliente() === $this) {
                $factura->setIdcliente(null);
            }
        }

        return $this;
    }
     public function __toString()
    {
        return $this->nombre;
    }

     public function getIngreso(): ?\DateTimeInterface
     {
         return $this->ingreso;
     }

     public function setIngreso(\DateTimeInterface $ingreso): self
     {
         $this->ingreso = $ingreso;

         return $this;
     }
}

src/Form/PresupuestoType.php
<?php

namespace App\Form;

use App\Entity\Facturas;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;



class PresupuestoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder            
            ->add('idclientesrelacion',HiddenType::class)
            ->add('fecha', DateType::class, array(
                    'widget' => 'single_text',
                    'html5' => false,
                    'attr' => ['class' => 'js-datepicker'],
            ))
            ->add('comentarios', CKEditorType::class, array(
                        'config' => array('toolbar' => 'basic'),
                ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Facturas::class,
        ]);
    }
}

templates/presupuesto/_delete_form.html.twig
<form method="post" action="{{ path('facturas_delete', {'id': factura.id}) }}" onsubmit="return confirm('¿Desea borrar y eliminar esta factura?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ factura.id) }}">
    <button class="btn btn-danger">Eliminar</button>
</form>

templates/presupuesto/_form.html.twig
{#{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}#}


<div class="mw1000 center-block">
 <div class="admin-form theme-primary">
                <div class="panel heading-border panel-primary">
                  <div class="panel-body bg-light">


 {{ form_start(form, {'attr': {'id': 'form-ui'}}) }}

  {{ form_widget(form.idclientesrelacion, {'attr': {'class': 'gui-input','placeholder':"RECIBO CAJA",'value': cliente }}) }}

                 <div id="spy1" class="section-divider mb40"><span></span></div>
		        	 <div class="row">



                      <div class="col-md-4">
                          <div class="section">
                            <label class="field">
                              {{ form_widget(form.fecha, {'attr': {'class': 'gui-input js-datepicker','placeholder':"FECHA"}}) }}

                            </label>
                          </div>
                        </div>

                      </div>

                   

                <div class="row">
                          <div class="col-md-12">
                            <div class="section">
                              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" title="Incluir productos de su preferencia">
                                  <span class=" fa fa-plus-square-o" aria-hidden="true"></span> Agregar Productos
                                </button>
                                <label class="btn btn-danger totales animated animated-short fadeInUp" >Total: 0</label>
                                <table class="table footable" id="data">
                                  <thead>
                                        <tr>
                                          <th>Producto</th>
                                          <th>Cantidad</th>
                                          <th>Precio</th>
                                          <th>Descuento %</th>
                                          <th>Sub-Total</th>
                                          <th>Orden de Produccion</th>
                                          <th>Comentarios</th>
                                          <th>Accion</th>                                          
                                        </tr>
                                  </thead>
                                  <tbody>
                                    {% if productosfacturados is defined %}
                                          
                                            {% for productos in productosfacturados %}
                                            <tr>
                                              <td>{{ productos.idproducto.nombre }}
                                                <input type="hidden" value='{{ productos.idproducto.id }}' name="productos[]">

                                                <input type="hidden" value='{{ productos.id }}' name="'idproducto[]" class="idproducto">
                                              </td>
                                              <td>{{ productos.cantidad }}
                                                <input type="hidden" value="{{ productos.cantidad }}" name="cantidad[]"></td>
                                              <td>{{ productos.precio }}<input type="hidden" value="{{ productos.precio }}" name="precio[]"></td>
                                               <td>{{ productos.descuento }} <input type="hidden" value="{{ productos.descuento }}" name="descuento[]"></td>
                                              <td>{{ productos.total }}</td>
                                              <td>{{ productos.ordenPromocion }}
                                                <input type="hidden" value="{{ productos.total }}" name="total[]">
                                                <input type="hidden" value="{{ productos.ordenPromocion }}" name="promocion[]"></td>
                                              <td>{{ productos.comentarios }}
                                                <input type="hidden" value="{{ productos.comentarios }}" name="comentarios[]"></td>
                                              <td><button type='button' class='btn btn-simple btn-danger btn-icon remove' title='Cancelar pedido'><span class='fa fa-remove'></span></button></td>
                                            </tr>
                                            {% endfor %}
                                          
                                    {% endif %}
                                  </tbody>
                                </table>
                          </div>  
                          </div>
                      </div>


                      <div class="row">
                      		<div class="col-md-12">
                      			<div class="section">
                            		<label class="field">
                              		{{ form_widget(form.comentarios, {'attr': {'class': 'gui-input','placeholder':"COMENTARIOS"}}) }}
                            		</label>
                          </div>	
                      		</div>
                      </div>
                      
                      		 
                      
                          <button class="btn btn-success">{{ button_label|default('Guardar') }}</button>

		        
{{ form_end(form) }} 


<!-- Modal -->
<div class="modal fade" id="exampleModal"  role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Carga de Productos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
{#        <div class="form-group">
            <label></label>
            <input class="form-control" type="number" name="cantidad" id="cantidad" placeholder="Cantidad de producto">
        </div>#}

        {{ form_start(form1, {'attr': {'class': 'pedidos'}}) }}

      <div class="form-group">
          {{ form_widget(form1.idproducto, {'attr': {'class': 'gui-input producto form-control','placeholder':"COMENTARIOS"}}) }}

        </div>

        <div class="form-group">
                    <label>Productos disponible</label>        

          {{ form_widget(form1.cantidadactual, {'attr': {'class': 'gui-input cantidadactual form-control','placeholder':"CANTIDAD ACTUAL","disabled":"disabled"}}) }}

        </div>

        <div class="form-group">

          {{ form_widget(form1.cantidad, {'attr': {'class': 'gui-input cantidad','placeholder':"Cantidad de producto"}}) }}
        </div>
      <div class="form-group">
        <label>Orden de Produccion</label>
          {{ form_widget(form1.ordenPromocion, {'attr': {'class': 'gui-input promocion','placeholder':"Orden de produccion","disabled":"disabled"}}) }}

      </div>

<div class="form-group">
          {{ form_widget(form1.comentarios, {'attr': {'class': 'gui-input comentarios','placeholder':"Comentarios"}}) }}
  </div>

  <div class="form-group">
  <label>Precio de venta</label>  
          {{ form_widget(form1.precio, {'attr': {'class': 'gui-input precio','placeholder':"Precio"}}) }}
  </div>

<div class="form-group">
  <label>Descuento %</label>

  {% if is_granted('ROLE_ADMIN') %} 
        {{ form_widget(form1.descuento, {'attr': {'class': 'gui-input descuento','placeholder':"Descuento"}}) }}
  {% else %}
          {{ form_widget(form1.descuento, {'attr': {'class': 'gui-input descuento','placeholder':"Descuento","disabled":"disabled"}}) }}
{% endif %}          
  </div>


<div class="form-group">
  <label>Sub-Total</label>
          {{ form_widget(form1.total, {'attr': {'class': 'gui-input total','placeholder':"Sub-Total","disabled":"disabled"}}) }}
  </div>




    
{{ form_end(form1) }}

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary cerramodal" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary ingresar">Agregar al cotizador</button>
      </div>
    </div>
  </div>
</div>

</div>
</div>
</div>

</div>

templates/presupuesto/edit.html.twig
{% extends 'template.html.twig' %}

{% block title %}Editar  Cotización{% endblock %}

 {% block addcss %}
  <style type="text/css">
    .precio,.total,.descuento,.promocion,.cantidadactual{
      color:red !important;
    }
  </style>
{% endblock %}
{% block header %}

 <header id="topbar" class="ph10">

             <div class="topbar-left">
            <ol class="breadcrumb">
              <li class="crumb-active"><a href="{{ path('facturas_index') }}">Presupuesto</a></li>                            
              <li class="crumb-trail">Editar registro</li>
            </ol>
          </div>
          
        </header>
         <header id="topbar" class="ph10">
          <div class="topbar-left">
            <ul class="nav nav-list nav-list-topbar pull-left">
              <li class="active"><a href="{{ path('cotizador_index') }}">Listado de presupuesto</a></li>
              <li>  {{ include('presupuesto/_delete_form.html.twig') }}</li>
              <li class="active" ><a target="_blank"  href="{{ path('cotizacion_pdf', {'id': factura.id}) }}">Imprimir Presupuesto</a></li>
              
            </ul>
          </div>
         
        </header>

<div class="content-header">
                <h2><b class="text-primary">Editar Cotización</b>
                </h2>
              
              </div>
{% endblock %}

{% block body %}
  

    {{ include('presupuesto/_form.html.twig', {'button_label': 'Actualizar'}) }}

  
{% endblock %}
{% block addscript %}

<script type="text/javascript">
     jQuery(document).ready(function (){

$(".precio").change(function() {
  console.log($(this).val());
    console.log($(".precioreal").val());
var precioreal = $(".precioreal").val();
var precio = $(this).val();
  if(parseFloat(precio) < parseFloat(precioreal) ){
    $(this).val('');
      toastr.error( 'El valor no puede se menor a precio de venta');
      $(this).focus();
      return false;

  }else{
  var total = parseFloat($(".precio").val())*parseFloat($(".cantidad").val());                
  $(".total").val(total);
  var suma = parseFloat($(".precioreal").val())+parseFloat($(".precio").val());
   $(".utilidad").val(suma)
 }

     });

$('#facturas_dias').removeAttr('required');
$("#facturas_dias").hide();
$('#facturas_reciboCaja').hide();

$("#facturas_ordenCompra").hide();
$('#facturas_ordenCompra').removeAttr('required');
$('#facturas_reciboCaja').removeAttr('required');


var forma = $( "#facturas_forma input:checked" ).val();
console.log(forma);
if(forma == "CR"){
       $("#facturas_dias").show();
       $("#facturas_ordenCompra").show();


    }else{
      $ ("#facturas_dias"). prop ('selectedIndex', 0);
       $("#facturas_dias").hide();
       $("#facturas_ordenCompra").hide();
       $("#facturas_ordenCompra").empty();
       $('#facturas_reciboCaja').hide();
      $('#facturas_reciboCaja').empty();


    }



$( "#facturas_forma input:radio" ).click(function() {
    if($(this).val() == "CR"){
       $("#facturas_dias").show();
         $("#facturas_ordenCompra").show();
                $('#facturas_reciboCaja').show();

    }else{
      $("#facturas_dias").prop ('selectedIndex', 0);
      $("#facturas_dias").hide();
      $("#facturas_ordenCompra").hide();
      $("#facturas_ordenCompra").empty();
      $('#facturas_reciboCaja').hide();
      $('#facturas_reciboCaja').empty();


    }
   });



var table = $('.footable').DataTable()
 var datossuma =  table.column( 4 ).data().sum();
  console.log(datossuma);
    $(".totales").html("Total: "+datossuma.toFixed(2));

      $( ".ingresar" ).click(function() {
          var t = $('.footable').DataTable();

            var productos =  $(".producto").val();
            var cantidad =  $(".cantidad").val();
            var precio = $(".precio").val();
            var total = $(".total").val();
            var promocion = $(".promocion").val();
            var comentarios = $(".comentarios").val();
             var porcentaje = $(".descuento").val();

             if (cantidad == 0 || cantidad == '')
            {
             toastr.error( "Debe ingresar cantidad valida de producto");
              return false;
            }
             if (comentarios == '')
            {
           /*  toastr.error( "Ingrese un comentario en su factura");
              return false;*/
            }

               if (porcentaje == '')
            {
             toastr.error( "Ingrese valor en porcentaje");
              return false;
            }



                   t.row.add( [
                    $(".producto option:selected").text()+"<input type='hidden' value='"+productos+"' name='productos[]'>",
                    $(".cantidad").val()+"<input type='hidden' value='"+cantidad+"' name='cantidad[]'>",
                    $(".precio").val()+"<input type='hidden' value='"+precio+"' name='precio[]'>",
                      $(".descuento").val()+"<input type='hidden' value='"+porcentaje+"' name='descuento[]'>",
                    $(".total").val(),
                    $(".promocion").val()+"<input type='hidden' value='"+promocion+"' name='promocion[]'>"+" "+"<input type='hidden' value='"+total+"' name='total[]'>",
                    $(".comentarios").val()+"<input type='hidden' value='"+comentarios+"' name='comentarios[]'>",
                     "<button type='button' class='btn btn-simple btn-danger btn-icon remove' title='Cancelar pedido'><span class='fa fa-remove'></span></button>"
                  ] ).draw( false );


                   $(".cerramodal").click();
                   $(".pedidos")[0].reset();

   var table = $('.footable').DataTable();
  var datossuma =  table.column( 4 ).data().sum();
  console.log(datossuma);
    $(".totales").html("Total: "+datossuma.toFixed(2));


          });








    $("#detalles_factura1_idproducto").change(function() {
       $.get( "{{ path('buscarproducto') }}", { iditems:$(this).val()}).done(function( data ) {

            if(data.length>0){ 
                  $(".precio").val(data[0]['precioventa']);         
                  produccion = data[0]['produccion'];
                  cantidadactual =  data[0]['disponibilidad'];


                  var total = data[0]['precioventa']*$(".cantidad").val();                
                  $(".total").val(total);
                  $(".cantidad").change();
                  $(".promocion").val(produccion);
                  $(".cantidadactual").val(cantidadactual);

              }
              
          });
    });




        $(".descuento").change(function() {
           var total = $(".precio").val()*$(".cantidad").val();
           $(".total").val(total);

           if($(this).val()>0){
              var totaldescuento = (total*$(this).val())/100;
              var descuento = $(".total").val()-totaldescuento;
              $(".total").val(descuento);
            }


           });
    
        $(".cantidad").change(function() {

             var producto =  $(".producto").val();
            var cantidad =  $(this).val();

            var total = $(".precio").val()*$(".cantidad").val();                
            $(".total").val(total);

       $.get( "{{ path('buscardescuento') }}", { id:$(this).val()}).done(function( data ) {

            if(data.length>0){ 
              console.log("total "+$(".total").val());

                  //$(".descuento").val(data[0]['porcentaje']);         
                 var totaldescuento = (total*data[0]['porcentaje'])/100;
                   descuento = $(".total").val()-totaldescuento;
                  $(".descuento").val(data[0]['porcentaje']);   

                  //var total = data[0]['precioventa']*$(".cantidad").val();                
                  $(".total").val(descuento);

              }else{
                 $(".total").val(total);
                $(".descuento").val(0);                         
              }
              
          });


        if(cantidad > 0){
        $.get( "{{ path('disponibilidad') }}", { producto:producto,cantidad:cantidad}).done(function( data ) {

            if(data.length == 0){ 
               $(".cantidad").val('');
                    $(".cantidad").focus();
                toastr.error( "Producto <b>"+ $(".producto option:selected").text()+ '</b> No hay producto disponible');
                
              }else{
                
                  if(cantidad > data[0]['cantidad']){
                    $(".cantidad").val('');
                    $(".cantidad").focus();
                    toastr.error( "Debe colocar una cantidad menor a "+ data[0]['cantidad']);
                    
                  }
              }
              
           });
      }
    });


    var table = $('.footable').DataTable();

    $('.footable tbody').on('click', '.remove', function () {

      var r = confirm("¿Desea quitar este registro?");
      if(r == true){
            var btn = this;
            $tr = $(this).closest('tr');
            var data = table.row($tr).data();          
            table.row($(btn).parents('tr')).remove().draw(false);
            var idfound =  $tr.find("td:eq(0)").find(".idproducto").val();
if(idfound > 0){


 $.ajax({      
      
      url:   '{{ url('detallesproductosremove') }}',
     type: "GET",
      data: { id : idfound },    
      beforeSend: function () {
      },
      success:  function (response) {
        
      }
    }); 

}

  var datossuma =  table.column( 4 ).data().sum();
  
    $(".totales").html("Total: "+datossuma.toFixed(2));

          }
      });

      });

</script>
{% endblock %}

templates/presupuesto/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}Cotizadores-Listados{% endblock %}



{% block header %}

        <header id="topbar" class="ph10">

             <div class="topbar-left">
            <ol class="breadcrumb">
              <li class="crumb-active"><a href="#">Cotizadores</a></li>                            
              <li class="crumb-trail">Listado</li>
            </ol>
          </div>
          
        </header>
         <header id="topbar" class="ph10">
          <div class="topbar-left">
            <ul class="nav nav-list nav-list-topbar pull-left">
              <li class="active"><a href="{{ path('clientes_index') }}">Clientes</a></li>
              
            </ul>
          </div>
         
        </header>
          
          
{% endblock %}
{% block body %}
{% for message in app.flashes('notice') %}
  


                <div class="alert alert-danger alert-dismissable">
                  <button type="button" data-dismiss="alert" aria-hidden="true" class="close"></button><i class="fa fa-remove pr10"></i><a href="#" class="alert-link">{{ message }}</a> 
                </div>
    
{% endfor %}
   <section id="content" class="table-layout animated fadeIn">
          <!-- begin: .tray-left-->
        
          <!-- begin: .tray-center-->
          <div class="tray tray-center">
            <!-- Panel with: Basic Footable-->
          
            <!-- Panel with: Data Filter-->
     
            <!-- Panel with: Pagination-->
            <div id="spy3" class="panel">
             
              <div class="panel-body pn">
<div class="table-responsive">

    <table class="table table-bordered mbn facturas">
        <thead>
            <tr>                
                <th>Fecha</th>
                 <th>Nombre del cliente</th>
                <th>Comentarios</th>
                <th>Total Presupuesto</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for factura in facturas %}
            <tr>                
                <td>{{ factura.fecha ? factura.fecha|date('d/m/Y') : '' }}</td>
                <td>{{ factura.idcliente.nombre }}</td>
                <td>{{ factura.comentarios|raw }}</td>
                <td>{{ factura.detallesFacturas|ingresomontos }} </td>
                <td>
                    <a title="Detalles" href="{{ path('cotizador_show', {'id': factura.id}) }}"><span class="glyphicon glyphicon-search"></span></a>
                    
                    <a title="Editar Cotizador" href="{{ path('cotizador_edit', {'id': factura.id,'cliente':factura.idcliente.id}) }}"><span class="glyphicon glyphicon-edit"></span></a>
                   

                    <a href="{{ path('facturas_edit', {'id': factura.id,'cliente':factura.idcliente.id}) }}" title="Aprobar"><span class="glyphicon glyphicon-paste"></span></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
        
    
  </table>
</div>
    </div>
</div>
</div>
</section>
{% endblock %}


    {% block addscript %}
    <script type="text/javascript">
          jQuery(document).ready(function () {



$('.facturas').DataTable({
           "bLengthChange":false,
                  "bFilter":true,
                  "bInfo":false,
                  "bAutoWidth":false,
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
        },

         dom: 'Bfrtip',
        buttons: [
            {
                extend: 'pdfHtml5',
                attr: { 
                  'class': 'btn btn-success',
                },
                text:'Imprimir PDF',
                //orientation: 'landscape',
                 //pageSize: 'LEGAL',
                exportOptions: {
                    columns: [ 0,1,2,3,5]
                },
                 download: 'open',
                 footer: true
                
            }
        ]



    });


  
    //$(".totales").html(datossuma.toFixed(2));

   });
    </script>
    {% endblock %}

templates/presupuesto/pdf.html.twig
<table border="1" >
	<tr>
			<th style="text-align:center">
				No
			</th>
			<th style="text-align:center">
				Descripciòn
			</th>
			<th style="text-align:center">
				Cantidad
			</th>
			<th style="text-align:center">
				Presentacion
			</th>
			<th style="text-align:center" >Precio Unitario</th>
			<th style="text-align:center">Precio Total</th>
			
	</tr>

{% set sumatoria = 0 %}
{% set contar = 0 %}

{% for factura in datos.detallesFacturas %}
{% set sumatoria = sumatoria + factura.total %}
{% set contar = contar + 1 %}

{% set preciounitario = factura.total/factura.cantidad %}
	<tr>

		<td>{{ contar }}</td>				
		<td>
			{{ factura.idproducto.nombre }}
		</td>
		<td style="text-align:center">
			{{ factura.cantidad }}{{ factura.idproducto.idmedidas.unidad }}
		</td>
		<td style="text-align:center">{{ factura.idproducto.cantidadPresentacion }}</td>
		<td style="text-align:center">
			{{ preciounitario|buscador(2, ',', '.') }}
		</td>		
		<td style="text-align:center">
			{{ factura.total|buscador(2, ',', '.') }}
		</td>
	</tr>

{% endfor %}

</table>

<p>Condiciones de oferta {{ datos.comentarios|raw }}</p>


<ul>
	<li>Precio en Quetzales </li>
    <li> Precio incluye IVA</li>
    <li> Forma de pago: En efectivo</li>
    <li> Oferta sujeta a disponibilidad y confirmación final</li>
    <li> Validez de la oferta: 10 días</li>
    <li> Forma de Entrega: Si el pedido es mayor de Q500 y dentro de perímetro de la capital, se ofrece reparto a domicilio sin cargo adicional. Si fuera menor se puede recoger en nuestras oficinas. </li>
</ul>
<p>Agradecemos su preferencia a nuestros productos, y esperando suplir sus necesidades,
A su servicio,
</p>
{#<p>{{ datos.idcliente.idUsuario.username }} - {{ datos.idcliente.idUsuario.email }}<br>#}
ventas@lamyaproducts.com<br>
Tel: 23616018 / 23099578
          